name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          entryPoint: 'sonar-scanner'
          args: >
            -Dsonar.organization=TaksheelSingh
            -Dsonar.projectKey=TaksheelSingh_ML_Spark_Competition
            -Dsonar.sources=src
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.language=py
            -Dsonar.inclusions=src/**/*.py
