name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: "taksheelsingh"
          projectKey: "TaksheelSingh_ML_Spark_Competition"
          projectBaseDir: "."
          token: ${{ secrets.SONAR_TOKEN }}
          args: "-Dsonar.sources=src -Dsonar.inclusions=src/**/*.py"
